/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({ 'checked' : IDL.Bool, 'text' : IDL.Text });

export const idlService = IDL.Service({
  'addTask' : IDL.Func([IDL.Text], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'removeTask' : IDL.Func([IDL.Text], [], []),
  'toggleTask' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({ 'checked' : IDL.Bool, 'text' : IDL.Text });
  
  return IDL.Service({
    'addTask' : IDL.Func([IDL.Text], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'removeTask' : IDL.Func([IDL.Text], [], []),
    'toggleTask' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };